#!/bin/bash

##
# Daemon to check if the authorization to the myuplink cloud still valid yet
#
# If not a notification will be created
##

if [ -x /usr/bin/logger ]
then
    /usr/bin/logger "This is just a sample DAEMON script from Sample Plugin"
fi

$LBHOMEDIR/bin/plugins/myuplink/checkAuth.pl > /dev/null 2>&1 &

exit 0
